
#redis地址
spring.redis.host=192.168.159.129
  #redis客户端lettuce配置
  #最大连接数，负数表示无限制
spring.redis.lettuce.pool.max-active=8
  #最大等待，负数表示无限制
spring.redis.lettuce.pool.max-wait=-1
  #shutdown超时
spring.redis.lettuce.shutdown-timeout=100
  #最大空闲连接数，负数表示无限制
spring.redis.lettuce.pool.max-idle=8
  #最小空闲连接数
spring.redis.lettuce.pool.min-idle=0


spring:
  redis:
    host: localhost
    lettuce:
      pool:
        max-active: 8
