spring:
  application:
    name: gateway
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    com.netflix: DEBUG
server:
  port: 8888
zuul:
  routes:
    provider:
      path: /provider/**
      serviceId: provider
