server:
  port: 9003
spring:
  application:
    name: consumer
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


#hystrix:
#  command:
#    HystrixClient#timeoutReq() :
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 500
#      circuitBreaker:
#        requestVolomeThreshold: 3



feign:
  hystrix:
    enabled: true # 打开feign对hystrix的支持
  compression:
    request:
      enabled: false # 是否对request开启压缩
    response:
      enabled: false # 是否对response开启压缩
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
      circuitBreaker:
        requestVolumeThreshold: 3

## 配置hystrix
#hystrix:
#  threadpool:
#    default:
#      coreSize: 10  #线程池核心线程数
#  command:
#    #IService#hello(): 设置某一个接口 default: 设置全部接口
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 500 #超时时间
#      circuitBreaker:
#        requestVolumeThreshold: 3  #当在配置时间窗口内达到此数量后，进行短路。默认20个
#        sleepWindowInMilliseconds: 5  #短路多久以后开始尝试是否恢复，默认5s
#        errorThresholdPercentage: 50  #出错百分比阈值，当达到此阈值后，开始短路。默认50%
