spring:
  application:
    name: gateway
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    com.netflix: DEBUG
server:
  port: 8888
zuul:
  routes:
    provider:
      path: /provider/** # 1、/** 匹配任意数量的字符和路径 2、/* 匹配任意数量的字符 3、/? 匹配单个字符
      serviceId: provider
#  retryable: true # 开启重试
#  add-host-header: true #解决重定向问题
#  ignored-patterns: /**/dev/** #忽略的接口
#  ignored-services: provider #忽略的服务，防止服务入侵
#  prefix: /pre #路由前缀
#  strip-prefix: false # 和prefix配合使用, true:实际地址还是没有前缀的； false:实际地址有这个前缀。

ribbon:
  eureka:
    enabled: false #禁止ribbon使用eureka负载均衡

