spring:
  application:
    name: gateway
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    com.netflix: DEBUG
server:
  port: 8888
zuul:
  routes:
    provider:
      path: /provider/** # 1、/** 匹配任意数量的字符和路径 2、/* 匹配任意数量的字符 3、/? 匹配单个字符
      url: http://localhost:9001/
  # 禁用filter语法
  # zuul.<SimpleClassName>.<filterType>.disable=true
  SendErrorFilter:
    error:
      disable: true
#      serviceId: provider
#  retryable: true # 开启重试
#  add-host-header: true #解决重定向问题
#  ignored-patterns: /**/dev/** #忽略的接口
#  ignored-services: provider #忽略的服务，防止服务入侵
#  prefix: /pre #路由前缀
#  strip-prefix: false # 和prefix配合使用, true:实际地址还是没有前缀的； false:实际地址有这个前缀。

#ribbon:
#  eureka:
#    enabled: false #禁止ribbon使用eureka负载均衡
gateway:
  groovy:
    pollingIntervalSeconds: 20 #扫面groovy文件间隔
    directories:
    - D:\develop\projects\study-space\groovy #指定groovy目录

#security:
#  basic:
#    enabled: false
#  oauth2:
#    client:
#      access-token-uri: http://localhost:7777/auth/oauth/token #令牌端点
#      user-authorization-uri: http://localhost:7777/auth/oauth/authorize #授权端点
#      client-id: gateway #OAuth2客户端ID
#      client-secret: secret #OAuth2客户端密钥
#    resource:
#      jwt:
#        key-value: springcloud123 #使用对称加密方式，默认算法为HS256
