spring:
#  cloud:
#    stream:
#      kafka:
#        binder:
#          brokers: http://localhost:19092

  kafka:
    bootstrap-servers: localhost:19092
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
    propagation-keys: user_name
  application:
    name: provider
  zipkin:
    sender:
      type: KAFKA
    base-url: http://127.0.0.1:9411


#eureka:
#  instance:
#    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
logging:
#  pattern:
#    level: [%X{traceId}/%X{spanId}] %-5p [%t] %C{2} - %m%n
  level:
    com.netflix: DEBUG
server:
  port: 9001
