
spring:
  application:
    name: provider
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    com.netflix: DEBUG
server:
  port: 9001